### ISSUE TITLE
ModelOptimizer for Deepspeech based on Tensorflow

### ISSUE THREAD

**Issue by raghuram-sathyamurthy** [opencv/dldt#143]
I am trying OpenVINO to work for speech_recognition based on Deepspeech tensorflow version from Mozilla.

Does ModelOptimizer works for speech related models? 
I know Kaldi is there, but i prefer Deepspeech as it is in TF

Still i tried to convert my model to IR format and got below error.

CMD: 
model-optimizer# python3 mo_tf.py --input_model ~/output_graph.pb --input input_node,input_lengths,previous_state_c,previous_state_h --output logits --input_shape [1,16,19,26],[1],[1,2048],[1,2048] --log_level=DEBUG

Error : 

[ 2019-05-01 11:53:08,076 ] [ DEBUG ] [ class_registration:164 ]  Run replacer <class 'extensions.front.input_cut.InputCut'>
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID (<class 'extensions.front.input_cut.InputCut'>)": 0
[ ERROR ]  Traceback (most recent call last):
  File "/root/model-optimizer/mo/utils/class_registration.py", line 167, in apply_replacements
    replacer.find_and_replace_pattern(graph)
  File "/root/model-optimizer/extensions/front/input_cut.py", line 33, in find_and_replace_pattern
    add_input_ops(graph, graph.graph['user_shapes'], True)
  File "/root/model-optimizer/mo/front/extractor.py", line 1102, in add_input_ops
    edges_to_remove)
  File "/root/model-optimizer/mo/front/extractor.py", line 987, in add_input_ops_helper_before_infer_input_port
    edges_to_remove.append((smart_node.in_node(port).id, smart_node.id))
  File "/root/model-optimizer/mo/graph/graph.py", line 139, in in_node
    return self.in_nodes(control_flow=control_flow)[key]
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/model-optimizer/mo/main.py", line 312, in main
    return driver(argv)
  File "/root/model-optimizer/mo/main.py", line 263, in driver
    is_binary=not argv.input_model_is_text)
  File "/root/model-optimizer/mo/pipeline/tf.py", line 127, in tf2nx
    class_registration.apply_replacements(graph, class_registration.ClassType.FRONT_REPLACER)
  File "/root/model-optimizer/mo/utils/class_registration.py", line 190, in apply_replacements
    )) from err
Exception: Exception occurred during running replacer "REPLACEMENT_ID (<class 'extensions.front.input_cut.InputCut'>)": 0

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------

**Comment by raghuram-sathyamurthy** [comment]
Found the document to convert Deepspeech to IR at https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_DeepSpeech_From_Tensorflow.html

But just following the command didn't work as it was throwing error that lstm_fused_cell/Gather or lstm_fused_cell/Gather_1 are not found. So i have to remove those nodes and then it got compiled. I am yet to run with OpenVINO.

model-optimizer# python3 ./mo_tf.py --input_model ~/output_graph.pb --freeze_placeholder_with_value "input_lengths->[1]" --input input_node,previous_state_h/read,previous_state_c/read --input_shape [1,16,19,26],[1,2048],[1,2048] --output raw_logits

**Comment by shubha-ramani** [comment]
Dear @raghuram-sathyamurthy com,
It worked perfectly fine for me on OpenVino 2019 R1.0.1 (2019.1.133). Please see my successful command below (Windows but it should be similar in Linux):
:\Users\sdramani\Downloads\deepspeech-0.3.0-models.tar\deepspeech-0.3.0-models\models>python "c:\Program Files (x86)\IntelSWTools\openvino_2019.1.133\deployment_tools\model_optimizer\mo_tf.py" --input_model output_graph.pb  --freeze_placeholder_with_value "input_lengths->[16]" --input "input_node,previous_state_h/read,previous_state_c/read" --input_shape [1,16,19,26],[1,2048],[1,2048] --output raw_logits,lstm_fused_cell/Gather,lstm_fused_cell/Gather_1 --log_level DEBUG

Make sure you put quotes around "input_node,previous_state_h/read,previous_state_c/read" and also your output is different from what is suggested (should work though since it's one of the legal outputs).

Thanks for using OpenVino !

Shubha

**Comment by raghuram-sathyamurthy** [comment]
It seems the step to convert to IR given at https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_DeepSpeech_From_Tensorflow.html used deepspeech v0.3.0 model. 

With that model, i was able to convert it to IR format and load them into Plugin

@shubha-ramani , have you or anyone tried inferring Deepspeech with OpenVINO?
If so, it would be easy for me to get a headstart.

**Comment by shubha-ramani** [comment]
Dear @raghuram-sathyamurthy 

Unfortunately, we don't have a sample which uses the deepspeech model right now. But you can study the below sample which is a speech recognition sample using Kaldi. Kaldi and Deepspeech are vastly different but perhaps you can get some ideas since Kaldi is also a speech processing model:
[https://docs.openvinotoolkit.org/latest/_inference_engine_samples_speech_sample_README.html](https://docs.openvinotoolkit.org/latest/_inference_engine_samples_speech_sample_README.html)

**Comment by Custler** [comment]
this script work perfect for me:
`@echo off
setlocal

set TMP_HOME=%~dp0

set DS_HOME=%TMP_HOME:~0,-1%

set DS_MODEL_VER=deepspeech-0.5.1-models

set MO_TF="%INTEL_OPENVINO_DIR%\deployment_tools\model_optimizer\mo_tf.py"

set OUT_GRAPH=%DS_HOME%\\%DS_MODEL_VER%\output_graph.pb
set ALPHBET=%DS_HOME%\\%DS_MODEL_VER%\alphabet.txt
set LM_BINARY=%DS_HOME%\\%DS_MODEL_VER%\lm.binary
set TRIE=%DS_HOME%\\%DS_MODEL_VER%\trie

if not exist %DS_HOME%\tb_log (
	mkdir %DS_HOME%\tb_log
)

python %MO_TF% ^
--input_model %OUT_GRAPH% ^
--freeze_placeholder_with_value "input_lengths->[16]" ^
--input "input_node,previous_state_h/read,previous_state_c/read" ^
--input_shape "[1,16,19,26],[1,2048],[1,2048]" ^
--output raw_logits,lstm_fused_cell/GatherNd,lstm_fused_cell/GatherNd_1 ^
--log_level WARNING ^
--tensorboard_logdir "%DS_HOME%\tb_log"

endlocal
exit /b 0
`

**Comment by mdabek** [comment]
--output raw_logits,lstm_fused_cell/GatherNd,lstm_fused_cell/GatherNd_1
This line is crucial. OpenVino documentation provides wrong (deprecated?) format. You need to change from Gather to GatherNd and from Gather_1 to GatherNd_1
