### ISSUE TITLE
Errors optimising a tensorflow model

### ISSUE THREAD

**Issue by fuzzyBatman** [opencv/dldt#153]
I have trained a Tensorflow Faster R-CNN model using the [tensorpack](https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN) repository. I am trying to optimise the model for use on Intel hardware. The backbone is an `ResNet50` with `FPN` enabled.

I ran the following
```
python3 /opt/intel/openvino/deployment_tools/model_optimizer/mo_tf.py \
    --input_model='train_log/faster_rcnn/frcnn_frozen.pb' \
    --output_dir='train_log/faster_rcnn/FP32' \
    --input='image' \
    --output='output/boxes' \
    --input_shape=[512,512,3] \
    --data_type=FP32 \
    --log_level=DEBUG
```
I am certain the input shape is `[512, 512, 3]`

The result is `Cannot infer shapes or values for node "output/map/while/SparseToDense"`

Full log:
```
[ 2019-05-19 18:33:49,051 ] [ DEBUG ] [ tf:243 ]  Replacing input '3' of the node 'output/map/while/SparseToDense' with placeholder 'output/map/while/SparseToDense/default_value_port_0_ie_placeholder'
[ ERROR ]  Cannot infer shapes or values for node "output/map/while/SparseToDense".
[ ERROR ]  indices[0] = [1] is out of bounds: need 0 <= index < [1]
         [[node output/map/while/SparseToDense (defined at /opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/front/tf/partial_infer/tf.py:115) ]]

Caused by op 'output/map/while/SparseToDense', defined at:
  File "/opt/intel/openvino/deployment_tools/model_optimizer/mo_tf.py", line 31, in <module>
    sys.exit(main(get_tf_cli_parser(), 'tf'))
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/main.py", line 312, in main
    return driver(argv)
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/main.py", line 263, in driver
    is_binary=not argv.input_model_is_text)
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/pipeline/tf.py", line 128, in tf2nx
    class_registration.apply_replacements(graph, class_registration.ClassType.MIDDLE_REPLACER)
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 167, in apply_replacements
    replacer.find_and_replace_pattern(graph)
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/extensions/middle/PartialInfer.py", line 31, in find_and_replace_pattern
    partial_infer(graph)
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/middle/passes/infer.py", line 130, in partial_infer
    node.infer(node)
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/front/tf/partial_infer/tf.py", line 60, in tf_native_tf_node_infer
    tf_subgraph_infer(tmp_node)
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/front/tf/partial_infer/tf.py", line 135, in tf_subgraph_infer
    all_constants, output_tensors = get_subgraph_output_tensors(node)
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/front/tf/partial_infer/tf.py", line 115, in get_subgraph_output_tensors
    tf.import_graph_def(graph_def, name='')
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 442, in import_graph_def
    _ProcessNewOps(graph)
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 235, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3433, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3433, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3325, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): indices[0] = [1] is out of bounds: need 0 <= index < [1]
         [[node output/map/while/SparseToDense (defined at /opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/front/tf/partial_infer/tf.py:115) ]]

[ ERROR ]  
[ ERROR ]  It can happen due to bug in custom shape infer function <function tf_native_tf_node_infer at 0x7f79e3a00158>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ 2019-05-19 18:33:49,062 ] [ DEBUG ] [ infer:194 ]  Node "output/map/while/SparseToDense" attributes: {'pb': name: "output/map/while/SparseToDense"
op: "SparseToDense"
input: "output/map/while/ExpandDims_port_0_ie_placeholder"
input: "output/map/while/Shape_port_0_ie_placeholder"
input: "output/map/while/ones_like_port_0_ie_placeholder"
input: "output/map/while/SparseToDense/default_value_port_0_ie_placeholder"
attr {
  key: "T"
  value {
    type: DT_BOOL
  }
}
attr {
  key: "Tindices"
  value {
    type: DT_INT64
  }
}
attr {
  key: "validate_indices"
  value {
    b: true
  }
}
, '_in_ports': {0, 1, 2, 3}, '_out_ports': {0}, 'kind': 'op', 'name': 'output/map/while/SparseToDense', 'op': 'SparseToDense', 'precision': 'FP32', 'infer': <function tf_native_tf_node_infer at 0x7f79e3a00158>, 'is_output_reachable': True, 'is_undead': False, 'is_const_producer': False, 'is_partial_inferred': False}
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "output/map/while/SparseToDense" node. 
 For more information please refer to Model Optimizer FAQ (<INSTALL_DIR>/deployment_tools/documentation/docs/MO_FAQ.html), question #38. 
[ 2019-05-19 18:33:49,063 ] [ DEBUG ] [ main:318 ]  Traceback (most recent call last):
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0] = [1] is out of bounds: need 0 <= index < [1]
         [[{{node output/map/while/SparseToDense}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/middle/passes/infer.py", line 130, in partial_infer
    node.infer(node)
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/front/tf/partial_infer/tf.py", line 60, in tf_native_tf_node_infer
    tf_subgraph_infer(tmp_node)
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/front/tf/partial_infer/tf.py", line 135, in tf_subgraph_infer
    all_constants, output_tensors = get_subgraph_output_tensors(node)
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/front/tf/partial_infer/tf.py", line 120, in get_subgraph_output_tensors
    result_tensor = sess.run(graph.get_tensor_by_name(out_tensor_name), feed_dict=feed_dict)
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0] = [1] is out of bounds: need 0 <= index < [1]
         [[node output/map/while/SparseToDense (defined at /opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/front/tf/partial_infer/tf.py:115) ]]

Caused by op 'output/map/while/SparseToDense', defined at:
  File "/opt/intel/openvino/deployment_tools/model_optimizer/mo_tf.py", line 31, in <module>
    sys.exit(main(get_tf_cli_parser(), 'tf'))
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/main.py", line 312, in main
    return driver(argv)
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/main.py", line 263, in driver
    is_binary=not argv.input_model_is_text)
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/pipeline/tf.py", line 128, in tf2nx
    class_registration.apply_replacements(graph, class_registration.ClassType.MIDDLE_REPLACER)
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 167, in apply_replacements
    replacer.find_and_replace_pattern(graph)
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/extensions/middle/PartialInfer.py", line 31, in find_and_replace_pattern
    partial_infer(graph)
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/middle/passes/infer.py", line 130, in partial_infer
    node.infer(node)
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/front/tf/partial_infer/tf.py", line 60, in tf_native_tf_node_infer
    tf_subgraph_infer(tmp_node)
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/front/tf/partial_infer/tf.py", line 135, in tf_subgraph_infer
    all_constants, output_tensors = get_subgraph_output_tensors(node)
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/front/tf/partial_infer/tf.py", line 115, in get_subgraph_output_tensors
    tf.import_graph_def(graph_def, name='')
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 442, in import_graph_def
    _ProcessNewOps(graph)
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 235, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3433, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3433, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3325, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): indices[0] = [1] is out of bounds: need 0 <= index < [1]
         [[node output/map/while/SparseToDense (defined at /opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/front/tf/partial_infer/tf.py:115) ]]


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 167, in apply_replacements
    replacer.find_and_replace_pattern(graph)
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/extensions/middle/PartialInfer.py", line 31, in find_and_replace_pattern
    partial_infer(graph)
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/middle/passes/infer.py", line 196, in partial_infer
    refer_to_faq_msg(38)) from err
mo.utils.error.Error: Stopped shape/value propagation at "output/map/while/SparseToDense" node. 
 For more information please refer to Model Optimizer FAQ (<INSTALL_DIR>/deployment_tools/documentation/docs/MO_FAQ.html), question #38. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/main.py", line 312, in main
    return driver(argv)
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/main.py", line 263, in driver
    is_binary=not argv.input_model_is_text)
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/pipeline/tf.py", line 128, in tf2nx
    class_registration.apply_replacements(graph, class_registration.ClassType.MIDDLE_REPLACER)
  File "/opt/intel/openvino_2019.1.144/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 184, in apply_replacements
    )) from err
mo.utils.error.Error: Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "output/map/while/SparseToDense" node. 
 For more information please refer to Model Optimizer FAQ (<INSTALL_DIR>/deployment_tools/documentation/docs/MO_FAQ.html), question #38.
```
Is it possible to do this conversion or is it only possible when using an object detection model from the tensorflow models repository?

**Comment by shubha-ramani** [comment]
Dear @fuzzyBatman 
For Tensorflow Object Detection API conversion, the command is more complicated than what you have shown.  
Please review the following documentation
[https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_Object_Detection_API_Models.html](https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_Object_Detection_API_Models.html)

Also there is a known bug with the *.json files which you pass into the 
**--tensorflow_use_custom_operations_config** switch. Please see download the attached *.zip file for the correct *.json. Drop these *.jsons into the following folder:
C:\Program Files (x86)\IntelSWTools\openvino_2019.1.<Version>\deployment_tools\model_optimizer\extensions\front\tf

Hope it helps. And thanks for using OpenVino !

Shubha

[tf_obj_det_jsons.zip](https://github.com/opencv/dldt/files/3198569/tf_obj_det_jsons.zip)

**Comment by fuzzyBatman** [comment]
This is of some help. Thank you. I used the Faster R-CNN config you provided.
However, the script asks for a pipeline config as well. I did not use the Tensorflow models.
The particular model I used is from Tensorpack and it has a ResNet50 backbone with FPN enabled.

I tried using [faster_rcnn_resnet50_coco.config](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/faster_rcnn_resnet50_coco.config) and ended up with the same error as above.

**Comment by fuzzyBatman** [comment]
NOTE: The model is not from the Tensorflow Object Detection API

**Comment by shubha-ramani** [comment]
@fuzzyBatman is there any reason you must use [https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN](https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN) as opposed to a validated and tested faster rcnn model ? What is the advantage of using tensorpack ? Please peruse our list of validated and tested models:
[http://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html](http://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html)

Thanks,

Shubha

**Comment by fuzzyBatman** [comment]
Sure, no problem.

I am training on a custom dataset in the COCO format.
A single class detector (red blood cells) with around 350-400 instances in a single image.

Example:
![output](https://user-images.githubusercontent.com/5787026/58051720-40224300-7b53-11e9-86cc-05e6b8a9bb75.png)

The above is an inference result (300-400 ms on a Nvidia Geforce GTX1050M, without any optimisations) from Tensorpack. Tensorpack seems easier to extend for use on custom datasets where the objects are not found in common visual databases like COCO or PASCAL VOC.

All that I have experienced with the Tensorflow object detection API, using the faster_rcnn_resnet50_coco model, is an error stating that `TensorLoss is NaN`. Also, training from scratch does not seem to be a major goal (or insufficient documentation provided) for the TF object detection API. Using a framework like Tensorpack or [Detectron](https://github.com/facebookresearch/Detectron), we can start with ImageNet weights and the model converges very quickly.

Correct me if I am wrong about the training from scratch part.

**Comment by shubha-ramani** [comment]
Dear @fuzzyBatman 
Wow that red-blood cell photo you uploaded gives me the heeby-jeebies ! 
I understand why you want to use Tensorpack but unfortunately it's not supported by Model Optimizer. It's absolutely possible to custom-train TF Object Detection API, though - lots of customers do it.  Official TensorFlow instructions are below:
[https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html)

Not sure what you mean by "training from scratch". Many customers re-train Tensorflow Object Detection API models to suit  their requirements.

Thanks,

Shubha

**Comment by fuzzyBatman** [comment]
@shubha-ramani Thank you for the reply.
I will check the link you sent.

I am closing this issue. The Tensorpack library uses certain tensor-ops that are currently not supported by Intel OpenVino TF or ONNX.
