### ISSUE TITLE
Unexpected exception happened. [ ERROR ] Please contact Model Optimizer developers and forward the following information: [ ERROR ] 'preprocessed_image_height'

### ISSUE THREAD

**Issue by roburst2** [opencv/dldt#34]
**python3 mo.py --input_model=/fine_tuned_model1/frozen_inference_graph.pb --output=detection_boxes,detection_scores,num_detections --tensorflow_use_custom_operations_config extensions/front/tf/legacy_faster_rcnn_support.json --tensorflow_object_detection_api_pipeline_config=/fine_tuned_model1/pipeline.config --input_shape=[1,256,256,3]**

I am getting below error while running the above command.

WARNING: the "SecondStagePostprocessorReplacement" is a legacy replacer that will be removed in the future release. Please, consider using replacers defined in the "extensions/front/tf/ObjectDetectionAPI.py"
[ ERROR ] -------------------------------------------------
[ ERROR ] ----------------- INTERNAL ERROR ----------------
[ ERROR ] Unexpected exception happened.
[ ERROR ] Please contact Model Optimizer developers and forward the following information:
[ ERROR ] 'preprocessed_image_height'
[ ERROR ] Traceback (most recent call last):
File "/opt/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/mo/main.py", line 321, in main
return driver(argv)
File "/opt/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/mo/main.py", line 263, in driver
mean_scale_values=mean_scale)
File "/opt/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/mo/pipeline/tf.py", line 171, in tf2nx
class_registration.apply_replacements(graph, class_registration.ClassType.FRONT_REPLACER)
File "/opt/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 102, in apply_replacements
replacer.find_and_replace_pattern(graph)
File "/opt/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/mo/front/tf/replacement.py", line 91, in find_and_replace_pattern
self.replace_sub_graph(graph, match)
File "/opt/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/mo/front/common/replacement.py", line 115, in replace_sub_graph
new_sub_graph = self.generate_sub_graph(graph, match)
File "/opt/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/extensions/front/tf/FasterRCNNs.py", line 243, in generate_sub_graph
config_attrs['input_height'] = graph.graph['preprocessed_image_height']
KeyError: 'preprocessed_image_height'

[ ERROR ] ---------------- END OF BUG REPORT --------------
[ ERROR ] -------------------------------------------------

**Comment by lazarevevgeny** [comment]
@roburst2 could you close the ticket if you successfully converted the model?

**Comment by roburst2** [comment]
issue resolved. legacy_faster_rcnn_support.json deprecated
