### ISSUE TITLE
PixelShuffle INT8 quantization error!

### ISSUE THREAD

**Issue by GuideWsp** [opencv/dldt#439]
Did any one have convert the FP32 of EDSR(pytorch) to INT8 mode?
Recently , we convert it, but it can't work. The reason is below, Fakequantization is not support 6-dim tensor, so if any one can give me a help ?
![image](https://user-images.githubusercontent.com/9530892/77818040-518c9200-710a-11ea-99ee-c8f239576abe.png)

**Comment by GuideWsp** [comment]
<img width="601" alt="Xnip2020-03-28_15-41-02" src="https://user-images.githubusercontent.com/9530892/77818080-a6c8a380-710a-11ea-98ec-bbb3df8e9641.png">

**Comment by GuideWsp** [comment]
![](https://tva1.sinaimg.cn/large/00831rSTgy1gd9oqotz22j30yc0r0t9i.jpg)

**Comment by brmarkus** [comment]
Can you reference which model exactly you used, where you got it from, which variant, please?

How have you tried to convert it, can you share the command lines of the tools, please?

After conversion, which application (ideally an OpenVINO/OpenModelZoo sample) have you tried and is failing after the conversion?

**Comment by GuideWsp** [comment]
I convert EDSR (https://github.com/thstkdgus35/EDSR-PyTorch) to IR model, and it test OK.
Then I try to quantize it to INT8 mode, the conversion json file is :
{
    /* Model */
    "model": {
        "model_name": "SRNet", // Model name
        "model": "/Users/happyer/workspace/OpenVINO-EDSR/edsr/edsr-pytorch.xml", // Path to model (.xml format),
        "weights": "/Users/happer/workspace/OpenVINO-EDSR/edsr/edsr-pytorch.bin", // Path to weights (.bin format),
    },
    /* Parameters of the engine used for model inference. */
    /* Post-Training Optimization Tool supports engine based on accuracy checker and custom engine.
       For custom engine you should specify your own set of parameters.
       The engine based on accuracy checker uses accuracy checker parameters. You can specify the parameters
       via accuracy checker config file or directly in engine section.
       More information about accuracy checker parameters can be found here:
       https://github.com/opencv/open_model_zoo/tree/master/tools/accuracy_checker */
    "engine": {
        "launchers":
        [
            {
                "framework": "dlsdk",
                "adapter": "super_resolution"
            }
        ],
        "datasets":
        [
            {
                "name": "imagenet_1000_classes",
                "reader": "pillow_imread",
                "data_source": "/Users/happyer/workspace/OpenVINO-EDSR/dataset",
                "preprocessing": [
                    {
                        "type": "bgr_to_rgb"
                    },
                ],
                "metrics": [
                    {
                        "name": "mse",
                        "type": "mse"
                    }
                ]
            }
        ]
    },
    /* Optimization hyperparameters */
    "compression": {
        "target_device": "CPU",
        "algorithms": [
            {
                "name": "DefaultQuantization",
                "preset": "performance",
                "params": {
                    "stat_subset_size": 300
                }
            }
        ]
    }
}

**Comment by GuideWsp** [comment]
I have tried the sample from OpenModelZoo and it test OK(FPR16, FP32, INT8)

**Comment by AlexKoff88** [comment]
Hi @GuideWsp,

What did you finally get? Does INT8 model work?

If it does not, can you please attach logs from the post-training tool?

**Comment by GuideWsp** [comment]
Thanks for your reply, I have upload the logs, dataset, code to the following:
[baidu]：链接:https://pan.baidu.com/s/1Q581GlfAPIEV5VWvXiI1dQ  密码:2aan
[Google]: https://drive.google.com/open?id=1jtgtWhJ1sC-S52Ji6Lo81HFd22lGvOo2

The steps of converting is following:
1. First, convert the pytorch model from "edsr_baseline_x2-1bc95232.pt" to IR FP32 model "edsr-baseline" with 
the following 
```
python export_model.py
```

2. Second, test the IR FP32model with following, and the result is ok.
```
python test_edsr_ir.py
```

3. Third, convert the FP model to INT8 model with the following, and will get the model in results.
```
pot -c edsr.json
```

4. Finally, when i test the INT8 model(I move the converted model to int folder), i get the follwing ERROR.
```
<openvino.inference_engine.ie_api.IENetwork object at 0x10cf46b70>
<openvino.inference_engine.ie_api.IEPlugin object at 0x12140fea0>
Traceback (most recent call last):
  File "/Users/wangshupeng/Desktop/edsr-openvino/test_edsr_ir_int8.py", line 88, in <module>
    main()
  File "/Users/wangshupeng/Desktop/edsr-openvino/test_edsr_ir_int8.py", line 51, in main
    exec_net, inputs, out_blob = load_ir_model()
  File "/Users/wangshupeng/Desktop/edsr-openvino/test_edsr_ir_int8.py", line 23, in load_ir_model
    exec_net = plugin.load(network=net)
  File "ie_api.pyx", line 1205, in openvino.inference_engine.ie_api.IEPlugin.load
  File "ie_api.pyx", line 1215, in openvino.inference_engine.ie_api.IEPlugin.load
RuntimeError: Unsupported number of dimensions for input at edge 0 in Quantize layer 150/fq_input_0
```

The information about 150/fq_input_0 is following:
```
<layer id="631" name="150/fq_input_0" type="FakeQuantize" version="opset1">
			<data levels="256"/>
			<input>
				<port id="0">
					<dim>1</dim>
					<dim>64</dim>
					<dim>200</dim>
					<dim>2</dim>
					<dim>200</dim>
					<dim>2</dim>
				</port>
				<port id="1"/>
				<port id="2"/>
				<port id="3"/>
				<port id="4"/>
			</input>
			<output>
				<port id="5" precision="FP32">
					<dim>1</dim>
					<dim>64</dim>
					<dim>200</dim>
					<dim>2</dim>
					<dim>200</dim>
					<dim>2</dim>
				</port>
			</output>
		</layer>
```


That is all the information about ERROR in Converting FP32 EDSR to INT8 model, I need your help.

Hoping for your reply and solutions.

**Comment by GuideWsp** [comment]
@AlexKoff88 I have a question: why it cannot convert the pytorch's pixel_shuffle to DepthToSpace and the tensorflow's depthtospace can be converted to DepthToSpace. 
The two op have the same fuction.

**Comment by AlexKoff88** [comment]
Thanks for the reproducing steps, we will look at it. Most probably the error was caused by the limitations of IE CPU runtime to infer the INT8 model with 6-dimensional tensor and not related to the quantization tool itself.

Regarding the last question. It seems that you have problems in the following path PyTorch->ONNX->IR. Where exactly do you have such a problem: in PyTorch->ONNX or ONNX->IR?

**Comment by GuideWsp** [comment]
Thanks for your reply.
1. The Conversion of Pytorch -> ONNX and ONNX -> IR(FP32) are all OK, and all test OK;
2. The Conversion of of IR(FP32) -> IR(INT) is OK, but test is error.

**Comment by ilya-lavrenov** [comment]
@dmitry-gorokhov @eshoguli do we have such limitations in CPU plugin?

**Comment by panshaohua** [comment]
@GuideWsp Have you solved your problem? I need to do sr.

**Comment by GuideWsp** [comment]
No, in final I have to select ncnn as the backend.

**Comment by panshaohua** [comment]
@GuideWsp But android is mainly supported on ncnn, PC is secondary.

**Comment by GuideWsp** [comment]
You can just use pytorch as backend on PC.

**Comment by panshaohua** [comment]
@GuideWsp it's slow with pytoch on cpu.
